version: '3.8'

services:
  bn-db:
    image: mongo
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          memory: 2G
  bn-management:
    image: bn-management
    build:
      context: .
    depends_on:
      - bn-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://bn-db:27017/bn-db
networks:
  default:
    name: my_custom_network