services:
  bn-db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: sadiodabasi  # Root kullanıcı adı
      MONGO_INITDB_ROOT_PASSWORD: 479408Aa  # Root kullanıcı şifresi
      MONGO_INITDB_DATABASE: bn-db

  bn-management:
    image: bn-management
    build:
      context: .
    depends_on:
      - bn-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://sadiodabasi:479408Aa@bn-db:27017/bn-db?authSource=admin

volumes:
  mongo-data:  # Volumeyi tanımladık

networks:
  default:
    driver: bridge  # Default network'u bridge olarak ayarladık